apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-zoeh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-mcwm-tenant/appstudio/dc-metro-map-zoeh@sha256:6990b306297b0dc8e770d9c0aff0516d74406c41777815c763d13a471b22d649
        name: my-nodejs
        resources: {}
status: {}
