apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-zoeh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-zoeh
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-zoeh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-zoeh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-zoeh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-mcwm-tenant/appstudio/dc-metro-map-zoeh@sha256:6990b306297b0dc8e770d9c0aff0516d74406c41777815c763d13a471b22d649
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
